include ../../../../template.mk

divide_test: divide_test.sv ../../divide.sv
sine_test: sine_test.sv ../../sine.sv
pulse_test: pulse_test.sv ../../pulse.sv
triangle_test: triangle_test.sv ../../triangle.sv
oscillator_test: oscillator_test.sv ../../oscillator.sv ../../divide.sv ../../sine.sv ../../triangle.sv ../../pulse.sv
